// +build !ignore_autogenerated

/*
Copyright 2016 The Kubernetes Authors All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1alpha1

import (
	api "k8s.io/kubernetes/pkg/api"
	unversioned "k8s.io/kubernetes/pkg/api/unversioned"
	v1 "k8s.io/kubernetes/pkg/api/v1"
	conversion "k8s.io/kubernetes/pkg/conversion"
)

func init() {
	if err := api.Scheme.AddGeneratedDeepCopyFuncs(
		DeepCopy_v1alpha1_Catalog,
		DeepCopy_v1alpha1_CatalogClaim,
		DeepCopy_v1alpha1_CatalogClaimList,
		DeepCopy_v1alpha1_CatalogClaimSpec,
		DeepCopy_v1alpha1_CatalogClaimStatus,
		DeepCopy_v1alpha1_CatalogEntry,
		DeepCopy_v1alpha1_CatalogEntryList,
		DeepCopy_v1alpha1_CatalogList,
		DeepCopy_v1alpha1_CatalogPosting,
		DeepCopy_v1alpha1_CatalogPostingList,
		DeepCopy_v1alpha1_LocalResourceSpec,
	); err != nil {
		// if one of the deep copy functions is malformed, detect it immediately.
		panic(err)
	}
}

func DeepCopy_v1alpha1_Catalog(in Catalog, out *Catalog, c *conversion.Cloner) error {
	if err := unversioned.DeepCopy_unversioned_TypeMeta(in.TypeMeta, &out.TypeMeta, c); err != nil {
		return err
	}
	if err := v1.DeepCopy_v1_ObjectMeta(in.ObjectMeta, &out.ObjectMeta, c); err != nil {
		return err
	}
	return nil
}

func DeepCopy_v1alpha1_CatalogClaim(in CatalogClaim, out *CatalogClaim, c *conversion.Cloner) error {
	if err := unversioned.DeepCopy_unversioned_TypeMeta(in.TypeMeta, &out.TypeMeta, c); err != nil {
		return err
	}
	if err := v1.DeepCopy_v1_ObjectMeta(in.ObjectMeta, &out.ObjectMeta, c); err != nil {
		return err
	}
	if err := DeepCopy_v1alpha1_CatalogClaimSpec(in.Spec, &out.Spec, c); err != nil {
		return err
	}
	if err := DeepCopy_v1alpha1_CatalogClaimStatus(in.Status, &out.Status, c); err != nil {
		return err
	}
	return nil
}

func DeepCopy_v1alpha1_CatalogClaimList(in CatalogClaimList, out *CatalogClaimList, c *conversion.Cloner) error {
	if err := unversioned.DeepCopy_unversioned_TypeMeta(in.TypeMeta, &out.TypeMeta, c); err != nil {
		return err
	}
	if err := unversioned.DeepCopy_unversioned_ListMeta(in.ListMeta, &out.ListMeta, c); err != nil {
		return err
	}
	if in.Items != nil {
		in, out := in.Items, &out.Items
		*out = make([]CatalogClaim, len(in))
		for i := range in {
			if err := DeepCopy_v1alpha1_CatalogClaim(in[i], &(*out)[i], c); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

func DeepCopy_v1alpha1_CatalogClaimSpec(in CatalogClaimSpec, out *CatalogClaimSpec, c *conversion.Cloner) error {
	out.Catalog = in.Catalog
	out.Entry = in.Entry
	return nil
}

func DeepCopy_v1alpha1_CatalogClaimStatus(in CatalogClaimStatus, out *CatalogClaimStatus, c *conversion.Cloner) error {
	out.State = in.State
	if in.CreatedResources != nil {
		in, out := in.CreatedResources, &out.CreatedResources
		*out = make([]v1.ObjectReference, len(in))
		for i := range in {
			if err := v1.DeepCopy_v1_ObjectReference(in[i], &(*out)[i], c); err != nil {
				return err
			}
		}
	} else {
		out.CreatedResources = nil
	}
	return nil
}

func DeepCopy_v1alpha1_CatalogEntry(in CatalogEntry, out *CatalogEntry, c *conversion.Cloner) error {
	if err := unversioned.DeepCopy_unversioned_TypeMeta(in.TypeMeta, &out.TypeMeta, c); err != nil {
		return err
	}
	if err := v1.DeepCopy_v1_ObjectMeta(in.ObjectMeta, &out.ObjectMeta, c); err != nil {
		return err
	}
	out.Catalog = in.Catalog
	out.Description = in.Description
	out.SourceNamespace = in.SourceNamespace
	return nil
}

func DeepCopy_v1alpha1_CatalogEntryList(in CatalogEntryList, out *CatalogEntryList, c *conversion.Cloner) error {
	if err := unversioned.DeepCopy_unversioned_TypeMeta(in.TypeMeta, &out.TypeMeta, c); err != nil {
		return err
	}
	if err := unversioned.DeepCopy_unversioned_ListMeta(in.ListMeta, &out.ListMeta, c); err != nil {
		return err
	}
	if in.Items != nil {
		in, out := in.Items, &out.Items
		*out = make([]CatalogEntry, len(in))
		for i := range in {
			if err := DeepCopy_v1alpha1_CatalogEntry(in[i], &(*out)[i], c); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

func DeepCopy_v1alpha1_CatalogList(in CatalogList, out *CatalogList, c *conversion.Cloner) error {
	if err := unversioned.DeepCopy_unversioned_TypeMeta(in.TypeMeta, &out.TypeMeta, c); err != nil {
		return err
	}
	if err := unversioned.DeepCopy_unversioned_ListMeta(in.ListMeta, &out.ListMeta, c); err != nil {
		return err
	}
	if in.Items != nil {
		in, out := in.Items, &out.Items
		*out = make([]Catalog, len(in))
		for i := range in {
			if err := DeepCopy_v1alpha1_Catalog(in[i], &(*out)[i], c); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

func DeepCopy_v1alpha1_CatalogPosting(in CatalogPosting, out *CatalogPosting, c *conversion.Cloner) error {
	if err := unversioned.DeepCopy_unversioned_TypeMeta(in.TypeMeta, &out.TypeMeta, c); err != nil {
		return err
	}
	if err := v1.DeepCopy_v1_ObjectMeta(in.ObjectMeta, &out.ObjectMeta, c); err != nil {
		return err
	}
	out.Catalog = in.Catalog
	out.Description = in.Description
	if in.LocalResources != nil {
		in, out := in.LocalResources, &out.LocalResources
		*out = new(LocalResourceSpec)
		if err := DeepCopy_v1alpha1_LocalResourceSpec(*in, *out, c); err != nil {
			return err
		}
	} else {
		out.LocalResources = nil
	}
	return nil
}

func DeepCopy_v1alpha1_CatalogPostingList(in CatalogPostingList, out *CatalogPostingList, c *conversion.Cloner) error {
	if err := unversioned.DeepCopy_unversioned_TypeMeta(in.TypeMeta, &out.TypeMeta, c); err != nil {
		return err
	}
	if err := unversioned.DeepCopy_unversioned_ListMeta(in.ListMeta, &out.ListMeta, c); err != nil {
		return err
	}
	if in.Items != nil {
		in, out := in.Items, &out.Items
		*out = make([]CatalogPosting, len(in))
		for i := range in {
			if err := DeepCopy_v1alpha1_CatalogPosting(in[i], &(*out)[i], c); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

func DeepCopy_v1alpha1_LocalResourceSpec(in LocalResourceSpec, out *LocalResourceSpec, c *conversion.Cloner) error {
	if in.Items != nil {
		in, out := in.Items, &out.Items
		*out = make([]v1.ObjectReference, len(in))
		for i := range in {
			if err := v1.DeepCopy_v1_ObjectReference(in[i], &(*out)[i], c); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}
